### ISSUE TITLE
iOS 15.x, Crash during Startup (Also happens on the Devoxx app)

### ISSUE THREAD

**Issue by FlorianKirmaier** [gluonhq/substrate#1047]
iOS 15.x, Crash during Startup

This does not happen with iOS 14.x.

It's both reproducible on the [devoxx app](https://github.com/devoxx/MyDevoxxGluon/commits/master) from the AppStore, and on my proprietary app.
I was not able to reproduce it on the "ResistorCalculator" App - probably because it starts very very fast.

I was able to reproduce it on all 5 iOS I could get my fingers on.
So it happens quite frequently. For some unknown reason - it sometimes happens nearly always, and other times it doesn't happen very often.

Some topics I found in another community, with a similar error:
 
 https://community.stencyl.com/index.php?issue=2024.20
 https://github.com/HaxeFoundation/hxcpp/issues/969#issuecomment-941127280

This suggests it correlates with how much is happening during the startup or when the application is used.
Especially because the complexity during startup correlates with the crash frequency. This explains why the ResistorCalculator app isn't affected.

My environment:
 - iOS 15.1
 - the latest version of the gluon gradle plugin `1.0.8`
 - Both iPad and iPhone
 - Couldn't test it on iOS15.x, because I didn't have a device available
 

To my current knowledge, this basically breaks GluonMobile for newer iOS devices, so I hope you can fix this quickly.
Maybe there is already a workaround known?

Here is the crash report generated by apple:
[crashlog.crash.txt](https://github.com/gluonhq/substrate/files/7584249/crashlog.crash.txt)

**Comment by FlorianKirmaier** [comment]
The Devoxx app crashes my IPad about 90% of the time, but on another iPhone, it only crashes like 20% of the time. So dependent on your device - it might crash more or less often.

**Comment by jperedadnr** [comment]
We recently fixed a crash on iOS 15 (https://bugs.openjdk.java.net/browse/JDK-8276915), that might be related. 
Can you try plugin 1.0.10-SNAPSHOT (with pluginRepository from url http://oss.sonatype.org/content/repositories/snapshots) ?

**Comment by FlorianKirmaier** [comment]
I'm using Gradle for the project.
I think you've forgotten to also release a SNAPSHOT build with a fix for
the Gradle plugin.
Can you make it available for the Gradle build? Then I will
immediately test it.

**Comment by jperedadnr** [comment]
Published https://oss.sonatype.org/content/repositories/snapshots/com/gluonhq/gluonfx-gradle-plugin/1.0.10-SNAPSHOT/

**Comment by FlorianKirmaier** [comment]
Thank you for the quick response! The new build is on the way.

**Comment by FlorianKirmaier** [comment]
Thank you, this seems to fix the problem!
I will do some final testing and then close the ticket.
I guess you should make a new stable version with the fix - because it seems to happen quite frequently, and it also happens on runtime.
