### ISSUE TITLE
Don't use LLVM backend on iOS by default

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/substrate#1095]
For now iOS uses LLVM backend, but with new GraalVM release, non LLVM backend works.

**Comment by LifeIsStrange** [comment]
@jperedadnr You don't have to answer but noob question but still I'll ask :)
I have never heard of LIR. How does GraalVM for IOS compile C code without LLVM ? What is LIR? Isn't it less optimized than LLVM?
I'm pretty sure it's this https://github.com/oracle/graal/tree/master/compiler/src/org.graalvm.compiler.lir.processor/src/org/graalvm/compiler/lir
but where is it documented ?
