### ISSUE TITLE
Provide a way to specify additional linker flags

### ISSUE THREAD

**Issue by kristofdho** [gluonhq/substrate#1101]
I would like to add additional linker flags similar to what native-image allows with the `-H:NativeLinkerOption` flag.

### Expected Behavior
* extra flags are added to the linker command.
* The option is also available in the maven plugin.

### Current Behavior
linker command is pretty much predefined and does not allow external additions.

### Context
I need to add extra exports to the produced executable, to work around this issue: #945 
Alternative solution: create my own patched version of substrate which hardcodes my required flags.

**Comment by lilili87222** [comment]
<linkerArgs>
<list>awt.dll</list>
</linkerArgs>

add linker arg compile fail


 BufferedImage targetBufferedImage = new BufferedImage(width, height, 5);

 if not add linker arg ,this code run fail
