### ISSUE TITLE
Windows Native EXE with externall DLL - JavaCPP loader crashes

### ISSUE THREAD

**Issue by Darlio** [gluonhq/substrate#1144]
### MY PROJECT :
**Uses 2 parts :**
- 1x 100% Java
- 1x External DLL coming from C++, which I built with JavaCPP

**I use Eclipse IDE** and the latest plugins / GraalVM as you will see in my POM and logs.

**All works fine with JavaFx goal : javafx:run**

**All works fine with Gluon goal : gluonfx:build** ([GluonBuild.log](https://github.com/gluonhq/substrate/files/8530981/GluonBuild.log))

### PROBLEM :
**If I make it on purpose to 'hide' the external DLL.**
All works fine with Gluon goal : gluonfx:nativerun ([GluonNativeRun_NoDLL.log](https://github.com/gluonhq/substrate/files/8531010/GluonNativeRun_NoDLL.log))

**With external DLL found, app crashes with a 'Error loading class org/bytedeco/javacpp/Loader'** ([GluonNativeRun_WithDLL.log](https://github.com/gluonhq/substrate/files/8531034/GluonNativeRun_WithDLL.log)
- Line 55 of log says `com.company.Loader.loadLibFromPath(Loader.java:74)` which is this part of code :
![image](https://user-images.githubusercontent.com/32061339/164460263-0ad29f68-6cae-4c78-8dfe-61d433ad36fb.png)
- Line 44 of log says `Caused by: java.lang.NoClassDefFoundError: Lorg/bytedeco/javacpp/Loader;` Which is the result of the problem on line 36 : `Error loading class org/bytedeco/javacpp/Loader`... But... my investigations show that the JAR and method path are there...

I want to switch from Launch4J to Gluon in order to be able to port my app to different OS. But to test the architecture of my app, I have built, from exact same source code, an executable JAR to see if Launch4J would also give any error... Which is NOT the case. My app runs smoothly.

THREE differences though between both EXE build origins, mainly coming from the Maven building, needed for Gluon :
1. I build separate JARs for Gluon (and reference them in my POM, attached [here](https://github.com/gluonhq/substrate/files/8531110/pom.txt))
2. These are NOT executable JARs (as it is in Launch4J, which has just that one)
3. The 'loading' part is done with a similar way, except that for Gluon EXE : the DLL is first 'extracted' from the resources inside the built JAR. Ending with the same instruction : `'System.load(temp.getAbsolutePath());'`.
![image](https://user-images.githubusercontent.com/32061339/164463217-a51e9ce5-f92d-4f80-86a6-c5637d241521.png)

### CONCLUSION :
I have tried really hard to understand why it would not work in Gluon.
- The POM does reference de JavaCPP.
- The path to the method inside the JavaCPP JAR does exists at the correct location.
- I'm irritated from the line 31 which says :`WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @531e85'` but I don't think this might be the issue.
- In the building part, all Classes / Fields / Methods are not what Gluon says 'reachable' (lines 51 - 55 of GluonBuild.log). Does this matter ?
 
Or... Is it that this is too complex for Gluon Substrate ?

Thank you for any help or clues... I'll investigate them !

**Comment by alaa-az** [comment]
Sorry I do not have an answer for this, but I had a similar issue, I had to use JNA to use some native library, and that time JNA was not working with Gluon or the Graal native image for that matter, I had to re write with JavaCPP  , it was hard and tricky but worked, after that newer Graal VM versions could detect JNA's reflections correctly and I flipped back to JNA and life is now wonderful.

**Comment by Darlio** [comment]
So nice of you for sharing your experience... As you could read, hidden in the lines, I directly used JavaCPP. But unfortunatly in my case, JavaCPP does not help. Maybe I'm architecturing the things wrongly,

I must say that I'm not familiar with JNI since I directly used JavaCPP (which encapsulates the JNI interface), how difficult is it to go from JavaCPP to JNI ?

**Comment by alaa-az** [comment]
Not JNI  ,  JNA  https://github.com/java-native-access/jna , anyway maybe is not useful in you case, and as for your question , did you add the dll in the resources config file ?

**Comment by Darlio** [comment]
That, my friend is a VERY GOOD comment !!! Which CONFIG file are you talking about ? Should it be in my POM ?
![image](https://user-images.githubusercontent.com/32061339/169272831-907f65db-a891-4653-b089-22effc001cea.png)

**Comment by alaa-az** [comment]
Oh now I see, the dll problem is one of many you will get if you do not scan your app for reflections and resources and JNI calls, any way run your app using **gluonfx:runagent**  click all buttons and use every feature, then a set of files will be automatically generated. this is very essential step to do, before you build.

**Comment by Darlio** [comment]
OMG ! You have pointed out a bottom process I have indeed not gone through ! Thank you ! And I will see why I didn't see this in the documentation process that I did try to follow very closely.
THANK YOU !

**Comment by alaa-az** [comment]
This is just a warning you will see only the first time you run the agent, coz it tries to merge with existing files not overwrite, just click all the buttons in you app and use every scenario possible, then after you close your app you will find that the files listed are created.

**Comment by Darlio** [comment]
As you said, the warnings no longer appear :-) !

I'm getting my build as usual, and when I run it, it has this new problem : https://github.com/oracle/graal/issues/2892

This happens now BEFORE the DLL' methods are used, so not sure if the original problem is solved or not. Will keep this feed posted.

Thank you again for your preciuous help ! 

Here is the log :
![image](https://user-images.githubusercontent.com/32061339/169522007-1765e6a4-a290-4955-a157-08f0d90f3bd9.png)

**Comment by alaa-az** [comment]
If you trying to use Media module from JavaFX I do not think you can compile to native yet on windows,  check "Table 3. Platform feature matrix for Native Images"  here https://docs.gluonhq.com/#_platforms

**Comment by Darlio** [comment]
Ohhhhh, I am trying indeed using this library : `javax.sound.sampled`

I suppose this is what they mean by 'Media' ?

My end goal is to build an APK for Android, would this be possible without checking the 'native Windows' is working ?

--> This is another topic tmho, and should be discussed either in PM or in another dedicated subject.

**Comment by alaa-az** [comment]
Actually `javax.sound.sampled` is part of the `Desktop` module, sorry cannot help here but if you trying to do some kind of an audio player you will need to use  `Gluon Attach` for Android and IOS. Sorry I do not have experience with that, anyway I think you should close this issue as it is not a substrate issue.

**Comment by Darlio** [comment]
This has solved the problem which is NOT a substrate issue :
https://github.com/gluonhq/substrate/issues/1144#issuecomment-1132806307

Thank you for your very precious help !
