### ISSUE TITLE
Gradle plugin

### ISSUE THREAD

**Issue by LifeIsStrange** [gluonhq/substrate#1162]
Hi :)
I think it would be nice to provide a Gradle plugin in addition to the maven one.
(all Android devs uses Gradle, and in general Gradle is widely used)
@jperedadnr

**Comment by jperedadnr** [comment]
While main focus is on the Maven plugin, there is already a Gradle plugin: https://github.com/gluonhq/gluonfx-gradle-plugin

**Comment by LifeIsStrange** [comment]
Oh that's great to hear!
Maybe you could mention it in the Readme for increased discoverability
