### ISSUE TITLE
Build on WindowsServerCore container fails

### ISSUE THREAD

**Issue by kristofdho** [gluonhq/substrate#1239]
Build fails on WindowsServerCore container, because `ie4uinit` dos not exist. I have not yet found a way to install this into the container as it doesn't have a Desktop UI, and ie4uinit is part of UI related stuff.

Fix would be to check if ie4uinit exists, and not run it if it doesn't.
Alternatively, ignore exceptions if it doesn't run, as it's only cosmetic.

### Expected Behavior

Build succeeds

### Current Behavior

This piece of code crashes:
https://github.com/gluonhq/substrate/blob/bd0f52be101a7e2ad3e237f2288855e59d307ca6/src/main/java/com/gluonhq/substrate/target/WindowsTargetConfiguration.java#L287-L291

Because `ie4uinit` does not exist.

### Steps to Reproduce

Do a build on WindowsServerCore.

### Your Environment
WindowsServerCore 2022 container, substrate 0.0.61

**Comment by jperedadnr** [comment]
Yes, it makes sense what you propose about doing a check to se if `ie4uinit` exists, though it might be more simple to put that code inside a try-catch and just log a warning if the process runner fails? Do you want to tae this?

**Comment by kkriske** [comment]
@jperedadnr see attached PR.
FYI, this is not that urgent for us, since we need to support older plugin versions on our CI environment anyway. So as a workaround we've added a noop ie4uinit.exe on the PATH, which circumvents the issue.

**Comment by kkriske** [comment]
@jperedadnr I'm sure your time is limited, but any chance to get this looked at? I'd like to get this included so we could possibly remove our workaround.
