### ISSUE TITLE
Android targetSdkVersion needs an update

### ISSUE THREAD

**Issue by molbertz** [gluonhq/substrate#1250]
Hello again. It seems like Google is now updating their requirement for new Android Versions yearly. Because just like last year they require a new Android version starting August 31st. This time the Target Version is: 34.
For reference this was the issue from last year:    #1227 

Kind regards,
Michael

**Comment by jperedadnr** [comment]
This can be tested now with plugin version 1.0.23-SNAPSHOT and
```
<pluginRepositories>
        <pluginRepository>
            <id>snapshot</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </pluginRepository>
    </pluginRepositories>
```
