### ISSUE TITLE
MacOS os.arch should be x86_64, not amd64

### ISSUE THREAD

**Issue by credmond** [gluonhq/substrate#1259]
MacOS "os.arch" should be x86_64, not amd64.

System.getProperty("os.arch") returns "amd64" from the native image that substrate produces, whereas any macOS JVM, or vanilla GraalVM native image, would correctly return "x86_64". And various libraries expect that behaviour.

This bug wreaks havoc where third-party code attempts to use "os.arch" to form part of how it looks up or loads its native libraries. E.g., /darwin/x86_64/something.dylib vs. /darwin/amd64/something.dylib (i.e., the latter would not exist).

This is very a common pattern.

**Comment by johanvos** [comment]
Thanks for reporting.
I'm surprised by this, as Substrate doesn't modify System properties set by either the VM or the classlibs. Hence, it seems to me if System.getProperty("os.arch") returns amd64, that this is returned by the VM (GraalVM) or the classlibs (OpenJDK).
We'll have to find out where that amd64 is coming from.

**Comment by credmond** [comment]
Gluon's GraalVM, when running as a JVM on macOS, returns x86_64. The native image on MacOS is returning amd64. I can say this with confidence...in fact I had to add a hack to change or.arch, so certain libraries would function.

 Whether or not it's GraalVM , substrate, or Gluon's modifications to GraalVM, that is the root cause... I am not sure with 100% confidence. But you can see a lot of logic in substrate about substituting "x86_64" with "amd64" (search the code for "amd64").

Let me do some more exploring. I was burnt out by the time I discovered this and the fact that you think I may be wrong has me doubting myself. I'll report back!

**Comment by credmond** [comment]
@johanvos  I was wrong on this one. It is GraalVM behaviour, present even to this day. I'll raise a bug with them. Seems like a bug to me.

**Comment by credmond** [comment]
Bug raised: https://github.com/oracle/graal/issues/9337
