### ISSUE TITLE
New features on substrate 63 documents 

### ISSUE THREAD

**Issue by Snoopy137** [gluonhq/substrate#1260]
I see a new commit was done yesterday to substrate and maven plugin but I cannot see what was added. Is there documentation available? Is there support for newer versions of tools such as maven and jdk?
Thanks in advance!

**Comment by jperedadnr** [comment]
Latest changes are listed here:
https://docs.gluonhq.com/#_what_is_new
https://github.com/gluonhq/substrate/releases/tag/0.0.63
