### ISSUE TITLE
Cannot type Chinese/Japanese/Korean characters on IOS. 

### ISSUE THREAD

**Issue by javasecret** [gluonhq/substrate#1267]
I am developing an iOS application using Gluon Mobile but have encountered a problem. When a TextField gains focus, the keyboard pops up, but this keyboard is different from the one configured in the iOS operating system. I have configured input methods for Chinese, Japanese Kana, Korean, French, etc., but in the app's keyboard, I cannot find the Chinese or Korean input methods when switching input methods. The Japanese Kana input method is available, but I cannot enter any Japanese characters into the TextField. How can I solve this problem?

I have searched through all the questions on StackOverflow but still have not found an answer. I am looking forward to a solution as soon as possible.

### Expected Behavior
Chinese / Korean input methods should be supported.

### Current Behavior
Cannot find the Chinese or Korean input methods when switching input methods on the app keyboard.

### Your Environment
IOS

**Comment by jperedadnr** [comment]
See https://stackoverflow.com/a/44520477/3956070

**Comment by javasecret** [comment]
It is not same as https://stackoverflow.com/a/44520477/3956070

This is cannot input Chinese/Japanese/Korean characters, no Chinese inputmethod on the keyboard. And that is Chinese words cannot display.
