### ISSUE TITLE
ios: code signing fails when remotely logged in

### ISSUE THREAD

**Issue by johanvos** [gluonhq/substrate#200]
I can only reproduce this when ssh from a linux machine into a mac.

mvn client:link fails, and the logs contain

[Sat Dec 14 19:48:06 CET 2019][FINE] Result for verify: true
[Sat Dec 14 19:48:06 CET 2019][SEVERE] Codesign validation failed

running 
mvn client:link
on the host machine itself works.

**Comment by jperedadnr** [comment]
Should be fixed with #335
