### ISSUE TITLE
Invalid or corrupt jarfile svm-hosted-native-darwin-amd64-19.3.0.tar.gz

### ISSUE THREAD

**Issue by maxum2610** [gluonhq/substrate#201]
When I include the following dependencies in order tp use substitutions and Features:

        <dependency>
            <groupId>org.graalvm.nativeimage</groupId>
            <artifactId>svm</artifactId>
            <version>19.3.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.graalvm.sdk</groupId>
            <artifactId>graal-sdk</artifactId>
            <version>19.3.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.graalvm.nativeimage</groupId>
            <artifactId>pointsto</artifactId>
            <version>19.3.0</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.oracle.svm.util</groupId>
                    <artifactId>org.objectweb.asm</artifactId>
                </exclusion>
            </exclusions> 
        </dependency>

in for example the HelloFXML sample, I get the following error:

[Sun Dec 15 09:24:52 CET 2019][FINE] compile command: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-19.3.0/Contents/Home/bin/native-image --no-server --report-unsupported-elements-at-runtime -Djdk.internal.lambda.eagerlyInitialize=false -H:+ExitAfterRelocatableImageWrite -H:TempDirectory=/Users/brunoposthuma/WORK/client-samples-master/Maven/HelloFXML/target/client/x86_64-darwin/gvm/tmp -H:+SharedLibrary -H:+AddAllCharsets -H:+AllowIncompleteClasspath -H:+ReportExceptionStackTraces -H:EnableURLProtocols=http,https -H:ReflectionConfigurationFiles=/Users/brunoposthuma/WORK/client-samples-master/Maven/HelloFXML/target/client/x86_64-darwin/gvm/reflectionconfig-x86_64-darwin.json -H:JNIConfigurationFiles=/Users/brunoposthuma/WORK/client-samples-master/Maven/HelloFXML/target/client/x86_64-darwin/gvm/jniconfig-x86_64-darwin.json -H:+PrintAnalysisCallTree -H:IncludeResources=.*/.*frag$ -H:IncludeResources=.*/.*fxml$ -H:IncludeResources=.*/.*css$ -H:IncludeResources=.*/.*gls$ -H:IncludeResources=.*/.*ttf$ -H:IncludeResources=.*/.*xml$ -H:IncludeResources=.*/.*png$ -H:IncludeResources=.*/.*jpg$ -H:IncludeResources=.*/.*jpeg$ -H:IncludeResources=.*/.*gif$ -H:IncludeResources=.*/.*bmp$ -H:IncludeResources=.*/.*license$ -H:IncludeResources=.*/.*json$ -H:IncludeResources=.*frag$ -H:IncludeResources=.*fxml$ -H:IncludeResources=.*css$ -H:IncludeResources=.*gls$ -H:IncludeResources=.*ttf$ -H:IncludeResources=.*xml$ -H:IncludeResources=.*png$ -H:IncludeResources=.*jpg$ -H:IncludeResources=.*jpeg$ -H:IncludeResources=.*gif$ -H:IncludeResources=.*bmp$ -H:IncludeResources=.*license$ -H:IncludeResources=.*json$ -H:IncludeResourceBundles=hellofx.hello,com/sun/javafx/scene/control/skin/resources/controls,com.sun.javafx.tk.quantum.QuantumMessagesBundle -Dsvm.platform=org.graalvm.nativeimage.Platform$DARWIN_AMD64 -cp /Users/brunoposthuma/WORK/client-samples-master/Maven/HelloFXML/target/classes:/Users/brunoposthuma/.m2/repository/org/graalvm/compiler/compiler/19.3.0/compiler-19.3.0.jar:/Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/objectfile/19.3.0/objectfile-19.3.0.jar:/Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/pointsto/19.3.0/pointsto-19.3.0.jar:/Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/svm/19.3.0/svm-19.3.0.jar:/Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/svm-hosted-native-darwin-amd64/19.3.0/svm-hosted-native-darwin-amd64-19.3.0.tar.gz:/Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/svm-hosted-native-linux-amd64/19.3.0/svm-hosted-native-linux-amd64-19.3.0.tar.gz:/Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/svm-hosted-native-windows-amd64/19.3.0/svm-hosted-native-windows-amd64-19.3.0.tar.gz:/Users/brunoposthuma/.m2/repository/org/graalvm/sdk/graal-sdk/19.3.0/graal-sdk-19.3.0.jar:/Users/brunoposthuma/.m2/repository/org/graalvm/truffle/truffle-api/19.3.0/truffle-api-19.3.0.jar:/Users/brunoposthuma/.m2/repository/org/graalvm/truffle/truffle-nfi/19.3.0/truffle-nfi-19.3.0.jar:/Users/brunoposthuma/.m2/repository/org/graalvm/truffle/truffle-nfi-native-darwin-amd64/19.3.0/truffle-nfi-native-darwin-amd64-19.3.0.tar.gz:/Users/brunoposthuma/.m2/repository/org/graalvm/truffle/truffle-nfi-native-linux-aarch64/19.3.0/truffle-nfi-native-linux-aarch64-19.3.0.tar.gz:/Users/brunoposthuma/.m2/repository/org/graalvm/truffle/truffle-nfi-native-linux-amd64/19.3.0/truffle-nfi-native-linux-amd64-19.3.0.tar.gz:/Users/brunoposthuma/.m2/repository/org/openjfx/javafx-base/13.0.1/javafx-base-13.0.1-mac.jar:/Users/brunoposthuma/.m2/repository/org/openjfx/javafx-base/13.0.1/javafx-base-13.0.1.jar:/Users/brunoposthuma/.m2/repository/org/openjfx/javafx-controls/13.0.1/javafx-controls-13.0.1-mac.jar:/Users/brunoposthuma/.m2/repository/org/openjfx/javafx-controls/13.0.1/javafx-controls-13.0.1.jar:/Users/brunoposthuma/.m2/repository/org/openjfx/javafx-fxml/13.0.1/javafx-fxml-13.0.1-mac.jar:/Users/brunoposthuma/.m2/repository/org/openjfx/javafx-fxml/13.0.1/javafx-fxml-13.0.1.jar:/Users/brunoposthuma/.m2/repository/org/openjfx/javafx-graphics/13.0.1/javafx-graphics-13.0.1-mac.jar:/Users/brunoposthuma/.m2/repository/org/openjfx/javafx-graphics/13.0.1/javafx-graphics-13.0.1.jar hellofx.HelloFXML --verbose
Error: Invalid or corrupt jarfile /Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/svm-hosted-native-darwin-amd64/19.3.0/svm-hosted-native-darwin-amd64-19.3.0.tar.gz
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1486)
Caused by: java.util.zip.ZipException: zip END header not found
com.oracle.svm.driver.NativeImage$NativeImageError: Invalid or corrupt jarfile /Users/brunoposthuma/.m2/repository/org/graalvm/nativeimage/svm-hosted-native-darwin-amd64/19.3.0/svm-hosted-native-darwin-amd64-19.3.0.tar.gz
	at com.oracle.svm.driver.NativeImage.processJarManifestMainAttributes(NativeImage.java:948)
	at com.oracle.svm.driver.NativeImage.processManifestMainAttributes(NativeImage.java:935)
	at com.oracle.svm.driver.NativeImage.addImageClasspathEntry(NativeImage.java:1407)
	at com.oracle.svm.driver.NativeImage.addCustomImageClasspath(NativeImage.java:1377)
	at com.oracle.svm.driver.DefaultOptionHandler.processClasspathArgs(DefaultOptionHandler.java:230)
	at com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:103)
	at com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1326)
	at com.oracle.svm.driver.NativeImage.processNativeImageArgs(NativeImage.java:1526)
	at com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:988)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1252)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1222)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1181)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1665)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1535)
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1436)
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1443)
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:52)
	at java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.util.jar.JarFile.<init>(JarFile.java:346)
	at java.util.jar.JarFile.<init>(JarFile.java:317)
	at java.util.jar.JarFile.<init>(JarFile.java:283)
	at com.oracle.svm.driver.NativeImage.processJarManifestMainAttributes(NativeImage.java:940)
	... 12 more
Compilation failed with result = 1
Compilation failed. The error should be printed above.

This is a graalvm bug and has been reported, but my question is should svm-hosted-native-darwin-amd64-19.3.0.tar.gz, which is defined as a dependency for the graal libs be included at all here?

NOTE: when using the unpatched client-maven-plugin which uses compiler 3.8.0 instead of 3.8.1
(see client-maven-plugin issue #64) you will get a NPE.

**Comment by jperedadnr** [comment]
No longer an issue (Substrate use Features itself). If it is, feel free to reopen.
