### ISSUE TITLE
Support java preference API

### ISSUE THREAD

**Issue by johanvos** [gluonhq/substrate#237]
The native code for the Java Preference API is in libprefs.a .
We already build this library for the supported platforms (including iOS), but Substrate doesn't link to it yet.

Related to https://github.com/gluonhq/client-gradle-plugin/issues/48

**Comment by xzel23** [comment]
Hi, thank you for the quick fix (the unresolved symbols for `_Java_java_util_prefs_MacOSXPreferences...` are now gone). However something is still missing (at least on MAC). It looks like the libprefs.a has to be also updated because it has an unresolved reference to `_JVM_ArrayCopy":

```
Undefined symbols for architecture x86_64:
  "_JVM_ArrayCopy", referenced from:
      _getStringsForNode in libprefs.a(MacOSXPreferencesFile.o)
ld: symbol(s) not found for architecture x86_64
```
