### ISSUE TITLE
Enable iOS-sim profile

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/substrate#252]
Using the iOS simulator is very convenient for getting screenshots in different resolutions required for submitting an app to the Apple store

**Comment by gboeve** [comment]
The iOS simulator is also needed to test an app on the different Apple devices. 
It is impossible for an individual developer to have all the different hardware available for testing.
Without extensive testing and screen dumps it is very difficult to get a stable app in the App Store.

**Comment by snelders** [comment]
In the meantime; Is there any workaround available (like manually copying the <appname>.app dir to you simulator maybe?

**Comment by HPTech2015** [comment]
My company is about to purchase Gluon Mobile and we don't want to purchase IOS devices.
Has this been fixed, or is there a workaround like what @snelders requested?

**Comment by jperedadnr** [comment]
There is ongoing [work](https://github.com/oracle/graal/pull/3340) in GraalVM that is required to have support for the iOS simulator on Substrate.

**Comment by jperedadnr** [comment]
Still experimental work, but we have iOS simulator working:

![ios-sim](https://user-images.githubusercontent.com/2043230/127905544-3eba29b6-7549-4583-84c5-edd73b4770f9.png)
