### ISSUE TITLE
Too verbose output from resourcesFeature

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/substrate#277]
When verbose is set to true, we add `-H:Log=registerResource:`.
However this also includes resources in the JavaFX jars, so there are around 100 resources, and it printouts a very long list to the console, without a managed logger:

```
 ...
[thread:77] scope: ForkJoinPool-9-worker-3.registerResource
  ResourcesFeature: registerResource: com/sun/javafx/scene/control/skin/modena/HTMLEditor-Underline-White.png
  ...
```

We could probably remove this or only send it to a report file?

**Comment by johanvos** [comment]
I don't see this as a problem? You only set verbose true if you want verbose output.
It would be nice if we have different levels, but even then, in some cases you want details about component A and nothing about component B....

**Comment by jperedadnr** [comment]
Not an issue
