### ISSUE TITLE
Support javafx.media on Linux

### ISSUE THREAD

**Issue by johanvos** [gluonhq/substrate#284]
Build the static libs for javafx media libraries on linux
Include the javafx media jar in Substrate, and link the static libs in the executable.

**Comment by maxum2610** [comment]
Are there any plans for a static lib version of jfxwebkit in the near future?

**Comment by johanvos** [comment]
@maxum2610  yes, but that is a different issue. Do you want to open one?

**Comment by maxum2610** [comment]
Yes, because the webview component depends on it. It should be done for all platforms.

**Comment by johanvos** [comment]
The question was a polite way to tell you it would be great if you can create the issue :)

**Comment by maxum2610** [comment]
Yes of course. And I did. Please see issue 312. Should I have created an issue per platform?

**Comment by johanvos** [comment]
I saw the issue, thanks for creating it :) I started working on it. No need to create one per platform, but I expect linux to be available first.

**Comment by maxum2610** [comment]
Ok, perfect. Thanks.
