### ISSUE TITLE
linux: missing zlib.h

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/substrate#306]
Even in modern distributions like Ubuntu 19.10, this library could be missing.

In that case, `gcc path/to/PosixDirectives.c ...` fails.

Doing:
```
sudo apt install zlib1g-dev
```
fixes the problem. 

This should be included in the error message and the Client documentation

**Comment by jskov** [comment]
also fixed by #366

**Comment by tiainen** [comment]
Fixed with #366
