### ISSUE TITLE
set user.home and java.home to reasonable values

### ISSUE THREAD

**Issue by johanvos** [gluonhq/substrate#313]
current situation on ios:
JAVA HOME: null
USER HOME: /var/mobile
StorageService root: /var/mobile/Containers/Data/Application/47CYY-XXX-ZZZBF0A/Library/gluon/

user.home should probably be /var/mobile/Containers/Application/47CYY-XXX-ZZZBF0A/Library/gluon/
and java.home should be user.home/java

**Comment by dubbadhar** [comment]
When can we possibly expect a fix?

**Comment by johanvos** [comment]
PR #478 provides the correct path for the user.home directory.
The java.home doesn't make sense in a static build.

**Comment by jperedadnr** [comment]
Fixed
