### ISSUE TITLE
Support jars in addition to classpaths for native-image generation

### ISSUE THREAD

**Issue by vlaaad** [gluonhq/substrate#322]
Hi! I want to use this project as a library to integrate it into a non-maven based toolchain. It would be useful for me to be able to provide an already-compiled jar file to this library for native image compilation — GraalVM's `native-image` seems to support that.

**Comment by jperedadnr** [comment]
Sorry for the late reply. If you can reevaluate your request, see if the latest version of Substrate is valid for you, and if you need some changes, please clarify what should be needed.

**Comment by vlaaad** [comment]
Thanks!
