### ISSUE TITLE
when client:compile fails, the result should not be SUCCESS

### ISSUE THREAD

**Issue by johanvos** [gluonhq/substrate#328]
Error: Image build request failed with exit status 1
Compilation failed with result = 1
Compilation failed. See error printed above.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by jperedadnr** [comment]
Fixed with Client-plugin https://github.com/gluonhq/client-maven-plugin/pull/123
