### ISSUE TITLE
Use pkg-config in LinuxTargetConfiguration

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/substrate#334]
LinuxTargetConfiguration runs a process to printout the transitive libraries of some other libraries like gtk+-3.0.

However, these libraries are already added to the link libs `linuxfxlibs`, and pkg-config is not used.

We have to use it instead, to add those libraries, and also to find out if the libs are installed or not.

**Comment by jskov** [comment]
This should be fixed by #366, if it ever gets to land :)

**Comment by tiainen** [comment]
Fixed with #366
