### ISSUE TITLE
HostServices.showDocument does not work on Mac

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/substrate#337]
HostServices.showDocument does not work on Mac. It fails with a message saying that 
_AWT is currently not supported on Substrate VM_. This is due to the fact that, only on the Mac, the `HostServicesDelegate` calls `Desktop.getDesktop().browse` to launch a browser. For other platforms `Runtime.getRuntime().exec` is used. I am wondering why this is not also done for the Mac. The single line `Runtime.getRuntime().exec(new String[]{"open", uri});` would do the trick and is even better than, e.g., the current Linux variant which just searches through a list of browser names and picks the first one it finds. This change would  fix the problem on Substrate VM and also remove the dependency on java.awt.Desktop. I have tested this on a standard VM as well as with substrate via the client-maven-plugin and it works without problem.

macOS 10.14.6
GraalVM 19.3.1
client-maven-plugin 0.1.15
jfx 15-ea+1

**Comment by jperedadnr** [comment]
Sorry for the late reply. Indeed it is weird that OpenJFX uses java.desktop only for Mac, and Runtime for the other platforms. This should be filed as a JBS issue that modifies the change that was done for https://bugs.openjdk.java.net/browse/JDK-8170624.
In the meantime, BrowseService in Attach 4.0.13 has now the implementation for desktop
https://github.com/gluonhq/attach/blob/master/modules/browser/src/main/java/com/gluonhq/attach/browser/impl/DesktopBrowserService.java

**Comment by mipastgt** [comment]
https://bugs.openjdk.java.net/browse/JDK-8274297
