### ISSUE TITLE
Find out what the minimal version of the linux linker should be

### ISSUE THREAD

**Issue by tiainen** [gluonhq/substrate#35]
The minimal version of the linker on linux (`ld`) might be as low as 2.26.1. Version 2.25.x or 2.26 might work as well, but that's currently not verified. Version 2.24 definitely does not work and will generate the following error during linking:

    /usr/bin/ld: ~/.gluon/substrate/javaStaticSdk/11-ea+8/linux-x86_64/labs-staticjdk/lib/static/libnet.a(linux_close.o): unrecognized relocation (0x2a) in section `.text.unlikely.getFdEntry.part.0'
    /usr/bin/ld: final link failed: Bad value
    collect2: error: ld returned 1 exit status
    Linking failed

**Comment by johanvos** [comment]
This should be detected and failed as soon as possible indeed (before we try to use linking)

**Comment by tiainen** [comment]
Further analysis showed that the minimal version of `ld` should be `2.26`.
