### ISSUE TITLE
File.mkdirs() returns false on Android

### ISSUE THREAD

**Issue by johanvos** [gluonhq/substrate#405]
The following app

```
File f = new File("dir");
boolean answer = f.mkdirs();
System.err.println(answer);
```

will return "false"

**Comment by jperedadnr** [comment]
This is not an issue, but a lack of permissions.

Adding  to the manifest:
```
<uses-permission a:name="android.permission.READ_EXTERNAL_STORAGE"/>
 <uses-permission a:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```
installing, giving storage permissions (the dialog doesn't show up?) and doing for instance:

```
File f = new File("/sdcard/Downloads/dir");
boolean answer = f.mkdirs();
System.err.println(answer);
```
returns `true`.

**Comment by johanvos** [comment]
So we can conclude this is not an error. The best approach to deal with this is another question.
