### ISSUE TITLE
[Github Actions] Flaky linux builds

### ISSUE THREAD

**Issue by abhinayagarwal** [gluonhq/substrate#432]
The builds on Ubuntu are flaky and unreliable. Sometimes they pass and sometimes they fail with:

> Gtk-WARNING **: 12:51:32.156: cannot open display: :99

This issue is always reported in [HelloFX test](https://github.com/gluonhq/substrate/pull/431/checks?check_run_id=500534328#step:9:829) which runs after HelloFXML tests and before HelloWorld / HelloGluon tests.

To fix this, we have already tried to [export DISPLAY to 99](https://github.com/gluonhq/substrate/actions/runs/53639410/workflow#L59), but it doesn't help.

**Comment by jperedadnr** [comment]
Didn't test it, but this [issue](https://github.com/cypress-io/cypress/issues/4334#issuecomment-571527321) has some possible fix?

**Comment by tiainen** [comment]
Is it not likely that Xvfb has stopped running after the first test for some unknown reason? Another thing that we could try is to start Xvfb manually in the background before running the tests:

    Xvfb :99 &
    export DISPLAY=:99
    ./gradlew -i test

**Comment by tiainen** [comment]
Fixed with #433
