### ISSUE TITLE
add new darwin lib

### ISSUE THREAD

**Issue by johanvos** [gluonhq/substrate#457]
https://github.com/oracle/graal/commit/3cf4c0651f78393f2e18aa032eea3ea1141b83f7 created a new lib libdarwin.a that is now needed to link with on darwin.

**Comment by tiainen** [comment]
Just a small question: the darwin library is not required when linking for the iOS target?

**Comment by johanvos** [comment]
I didn't know with 100% guarantee until now, as the mismatched cap-files prohibited testing. But now I know, and yes, it is needed there too.

**Comment by jperedadnr** [comment]
Fixed with #458 and #461
