### ISSUE TITLE
Random crashes on Android

### ISSUE THREAD

**Issue by AlmasB** [gluonhq/substrate#459]
I've built a few game samples, which all use FXGL and Gluon client plugin to run on Android. They all compile and run fine. However, eventually each game crashes with no clear error message, but something along the lines of:

```
[Wed Mar 18 11:06:29 GMT 2020][INFO] [SUB] W/ActivityManager( 3679): setHasOverlayUi called on unknown pid: 13735
[Wed Mar 18 11:06:33 GMT 2020][INFO] [SUB] --------- beginning of crash
[Wed Mar 18 11:06:34 GMT 2020][INFO] [SUB] W/ActivityManager( 3679): crash : com.almasb.GeometryWars,0
[Wed Mar 18 11:06:34 GMT 2020][INFO] [SUB] W/ActivityManager( 3679):   Force finishing activity com.almasb.GeometryWars/com.gluonhq.helloandroid.MainActivity
[Wed Mar 18 11:06:34 GMT 2020][INFO] [SUB] W/ActivityManager( 3679): setHasOverlayUi called on unknown pid: 14465
[Wed Mar 18 11:06:35 GMT 2020][INFO] [SUB] W/ActivityManager( 3679): Ignoring remove of inactive process: ProcessRecord{1975286 0:com.almasb.GeometryWars/u0a180}
```

No similar issues occur when running natively on Linux or Mac (via `client:build` and run). I haven't yet tested with iOS.

Link: https://github.com/AlmasB/FXGLGames
Projects Breakout and GeometryWars are set up and ready for `mvn clean client:build`, just need to update `<target>android</target>`.

Interestingly, Breakout seems to "survive" longer than GeometryWars before the crash occurs. I also tested with a simpler project - Drop, which can run even longer before the crash.

Tested with Samsung S7 and OnePlus 7 Pro.

**Comment by dubbadhar** [comment]
i saw this occuring when i use `stage.setMaximize(true)`

**Comment by AlmasB** [comment]
Tested with same (as mentioned above) software and hardware, but now using client maven plugin 0.1.31-SNAPSHOT, attach 4.0.8 and graalvm CE 20.3.0-dev-20200731_0209. Cannot reproduce crashes, so this must have got fixed at some point.
