### ISSUE TITLE
Text rendering issue on Android

### ISSUE THREAD

**Issue by abhinayagarwal** [gluonhq/substrate#508]
Gluon Mobile has text rendering issues on Android 10 running on OnePlus 7. This could be specific to OnePlus as we have had similar issue in the past for OnePlus devices.

Please check the image:

<img alt="Android-text-bug" src="https://user-images.githubusercontent.com/3197675/78772121-e61aae00-79ae-11ea-8356-9f87437f70ca.jpg" width=300>

**Comment by jperedadnr** [comment]
Probably not an issue for Substrate? Some Android vendors don't include all Roboto font variants, and using a different font should work.
