### ISSUE TITLE
Windows: Error: Illegal char <"> at index 0

### ISSUE THREAD

**Issue by blackjyn** [gluonhq/substrate#568]
I'm trying to compile [the samples](https://github.com/gluonhq/client-samples) with the following env:
- Windows x64
- GraalVM v20
- MSVC 2017

All are fine , I can even see that Graal has compiled the source to *.class file under the target/* folder.
However when it tried to compile with **native-image** I got:
`[Fri May 01 13:08:44 ICT 2020][INFO] We will now compile your code for x86_64-mi
crosoft-windows. This may take some time.
java.nio.file.InvalidPathException: Illegal char <"> at index 0: "D:\Repo\JavaFX
\gluon-client-substrate-samples\Maven\HelloFXML\target\classes
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.ja
va:182)
[INFO] ------------------------------------------------------------------------
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:1
53)
[INFO] BUILD FAILURE
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:7
7)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
[INFO] ------------------------------------------------------------------------
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java
:229)`

So I then [in probably damn stupid way] tried to compile it manually using native-image to that resulted class location but no luck. 

Solution?

**Comment by tiainen** [comment]
Only basic java programs (aka non-JavaFX) are supported at the moment.
See #205 for tracking progress on JavaFX support on Windows.

**Comment by tiainen** [comment]
Fixed with #581

**Comment by blackjyn** [comment]
Apparently , this issue still persists even when upgrading  to GraalVM v21 
![gluon-graalvm-dontwork](https://user-images.githubusercontent.com/6046191/107755307-31cb8000-6d55-11eb-840f-237472136a5c.png)

**Comment by jperedadnr** [comment]
That looks like a different issue. Check your pom and make sure that there is no extra `>` symbol in your project's name. Also make sure that you are using the latest Gluon plugin for your IDE.

**Comment by blackjyn** [comment]
Why should I add `>` in my project name?
The project was entirely generated with Gluon for Eclipse

**Comment by jperedadnr** [comment]
I didn't say you added it, but to review the pom for the project generated. Using the latest plugin it shouldn't happen but there was an issue before.

**Comment by blackjyn** [comment]
OMG! Thank you!
I didn't even touch Maven's pom.xml generated with Eclipse but , hey.. there's extra `>` there exactly at `<name>` tag!

Thanks it has been compiled successfully!
