### ISSUE TITLE
JNI_OnLoad not found for libextnet.a

### ISSUE THREAD

**Issue by johanvos** [gluonhq/substrate#573]
There is no JNI_OnLoad for this in OpenJDK, however a System.loadLibrary is performed.

**Comment by galderz** [comment]
Hi, I've also discovered an issue related to this on Quarkus. I've asked GraalVM team why these changes happened (see [here](https://github.com/oracle/graal/commit/8fb8fc502411b3c84308ff5cda4d6c1f775f3920)). Based on the response there I'll check with OpenJDK developers if there's a need to add https://github.com/graalvm/labs-openjdk-11/commit/9eee9ee40aeb69c6c85d1492a3369c232807f3c0 to OpenJDK too.
