### ISSUE TITLE
JAVAFX_STATIC_SDK is not defined on windows

### ISSUE THREAD

**Issue by tsatatwer** [gluonhq/substrate#585]
I have tried the new release  **substrate 0.0.22** on windows I got this :

`FAILURE: Build failed with an exception.
Build file 'D:\Javafx Native\substrate-0.0.22\substrate-0.0.22\test-project\build.gradle' line: 20
A problem occurred evaluating project ':helloFX'.
 JAVAFX_STATIC_SDK is not defined or is pointing to a non-existing directory: null`

Where is the JAVAFX_STATIC_SDK ??? I am missing some thing...

**Comment by tiainen** [comment]
The `test-project` is used by our CI tools to for integration testing and should not be used as a testbed by users that aren't developing substrate. If you want to try a sample, please use the [client-samples](https://github.com/gluonhq/client-samples) project instead.

**Comment by tsatatwer** [comment]
OK ...we are waiting patiently for windows support ....thanks for the great efforts on that.

**Comment by phamvanthanh** [comment]
@tsatatwer 

I have tried all 4 samples here https://github.com/gluonhq/client-samples.
All work.
