### ISSUE TITLE
IOS app using Reactor Netty and SSL will not compile to a native-image with gluon client-maven-plugin

### ISSUE THREAD

**Issue by acgrimes** [gluonhq/substrate#619]
I have an application that I am trying to build and deploy to a linux desktop as a native-image. After testing it will be deployed to an iphone ios operating system. This client app is using Reactor Netty and SSL to communicate with a server. Using the gluon client-maven-plugin the client:compile fails. It is failing due to build time initialization of some classes. Regardless of the --initialize-at-run-time arguments provided, the build fails.
Interestingly, if I use another pom.xml file with the Graalvm native-image-maven-plugin and the same --initialize-at-run-time arguments, the same client app builds and runs on a linux box. But I need a native image that can be deployed to IOS, so I need the gluon client-maven-plugin to build. I have attached the gluon pom.xml, the gluon client.debug log and the Graalvm pom.xml. 
Let me know if you need more information. Any help will be appreciated.
Here is the Client class:

public class Client implements Runnable {

    private static final Logger log = Logger.getLogger(Client.class.getSimpleName());

    public static void main(String[] args) throws InterruptedException {

        new Thread(new Client()).start();

    }

    public void run() {

        Consumer<ByteBuf> onSuccess = (ByteBuf response) -> {
            byte[] respByteArr;
            if(response.hasArray()) {
                respByteArr = response.array();
            } else {
                respByteArr = new byte[response.readableBytes()];
                response.duplicate().readBytes(respByteArr);
            }
            ElectionResponse electionResponse = SerializationUtils.deserialize(respByteArr);
            log.info("response in onSuccess: "+electionResponse);

        };
        Consumer<Throwable> onError = (Throwable ex) -> {
            ex.getMessage();
        };

        Runnable onCompletion = () -> {
            System.out.println("Message Completed");

        };
        ElectionRequest electionRequest = new ElectionRequest("aRequest");
        byte[] requestBytes = SerializationUtils.serialize(electionRequest);
        ByteBuf requestByteBuf = Unpooled.copiedBuffer(requestBytes);

        try {
            final SslContext ctx = SslContextBuilder.forClient()
                    .trustManager(InsecureTrustManagerFactory.INSTANCE)
                    .sslProvider(SslProvider.OPENSSL)
                    .build();

            HttpClient.create()
                    .tcpConfiguration(tcpClient -> tcpClient.host("localhost"))
                    .port(61005)
                    .protocol(HttpProtocol.HTTP11)
                    .secure(ssl -> ssl.sslContext(ctx))
                    .post()
                    .uri("/echo")
                    .send(Mono.just(requestByteBuf))
                    .responseContent()
                    .aggregate()
                    .subscribe(onSuccess, onError, onCompletion);
        } catch(SSLException ssl) {
            ssl.printStackTrace();
        }
        try {
            Thread.sleep(10000);
        } catch(InterruptedException ie) {
            ie.printStackTrace();
        }
    }
}

[gluon_pom.pdf](https://github.com/gluonhq/substrate/files/4682607/gluon_pom.pdf)
[Graalvm_pom.pdf](https://github.com/gluonhq/substrate/files/4682613/Graalvm_pom.pdf)
[client-debug0.log](https://github.com/gluonhq/substrate/files/4682619/client-debug0.log)

**Comment by jperedadnr** [comment]
You should be able to add any required native image option to the client plugin:

```
<configuration>
                    <nativeImageArgs>
                        <arg>--initialize-at-run-time=reactor.netty.tcp.TcpUtils</arg>
...
                    </nativeImageArgs>
...
```

**Comment by acgrimes** [comment]
I did using this syntax
``
<nativeImageArg>--initialize-at-run-time=reactor.netty.tcp.TcpUtils</nativeImageArg>
``
but the build fails with an indication that the build does not see the --initialize-at-run-time args, if fact it warns that these classes should not be initialized at build time. The particular class it is complaining about is java.net.Inet6Address or a class that is calling it. Yet when I put --initialize-at-run-time=java.net.Inet6Address as an arg it seems to be ignored. If you take a look at the gluon pom.xml and the client_debug.log you will see this.

**Comment by acgrimes** [comment]
Using:
``
<arg>--initialize-at-run-time=java.net.Inet6Address</arg>
``
I am getting:
`[INFO] --- client-maven-plugin:0.1.24:compile (default-cli) @ iPhoneClient ---
[Tue May 26 10:39:30 EDT 2020][INFO] ==================== COMPILE TASK ====================
[Tue May 26 10:39:30 EDT 2020][INFO] We will now compile your code for x86_64-linux-linux. This may take some time.
[Tue May 26 10:39:37 EDT 2020][INFO] [SUB] [client.client:112800]    classlist:   6,259.63 ms,  1.19 GB
[Tue May 26 10:39:38 EDT 2020][INFO] [SUB] [client.client:112800]        (cap):     582.02 ms,  1.19 GB
[Tue May 26 10:39:39 EDT 2020][INFO] [SUB] [client.client:112800]        setup:   1,919.10 ms,  1.19 GB
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB] [client.client:112800]     analysis:   9,920.94 ms,  2.68 GB
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB] Error: Classes that should be initialized at run time got initialized during image building:
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB]  java.net.Inet6Address the class was requested to be initialized at build time (from the command line). java.net.Inet6Address has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of java.net.Inet6Address
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB] 
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB] com.oracle.svm.core.util.UserError$UserException: **Classes that should be initialized at run time got initialized during image building**:
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB]  **java.net.Inet6Address the class was requested to be initialized at build time (from the command line)**. java.net.Inet6Address has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of java.net.Inet6Address
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB] 
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB]      at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB]      at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:510)
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB]      at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:187)
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:720)
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB]      at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:720)
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[Tue May 26 10:39:49 EDT 2020][INFO] [SUB] Error: Image build request failed with exit status 1
[Tue May 26 10:39:49 EDT 2020][SEVERE] Process compile failed with result: 1
Check the log files under /home/linuxlp/ideaProject/java/reactorNetty/gluonhqPlugin/client/target/client/x86_64-linux/gvm/log
And please check https://docs.gluonhq.com/client/ for more information.
[Tue May 26 10:39:49 EDT 2020][INFO] Logging process [compile] to file: /home/linuxlp/ideaProject/java/reactorNetty/gluonhqPlugin/client/target/client/log/process-compile-1590503989427.log
[Tue May 26 10:39:49 EDT 2020][SEVERE] Compiling failed.
Check the log files under /home/linuxlp/ideaProject/java/reactorNetty/gluonhqPlugin/client/target/client/x86_64-linux/gvm/log
And please check https://docs.gluonhq.com/client/ for more information.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.923 s
[INFO] Finished at: 2020-05-26T10:39:49-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.24:compile (default-cli) on project iPhoneClient: Compiling failed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
**`**

**Comment by jperedadnr** [comment]
I'm closing this issue now. 
Feel free to reopen it if you think this is still not solved with the latest Substrate and GraalVM versions.
