### ISSUE TITLE
Error creating fragment shader

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/substrate#641]
When I try to use a MeshView I get lots of exceptions saying "Error creating fragment shader" and then the application hangs. See attached log file for more details. What makes me wonder is the message that the process is running out of texture memory which I can hardly believe because I'd say my texture use is quite moderate. The following lines then seem to indicate an actual programming error.

Samsung Galaxy Tab S4
client-maven-plugin 0.1.26
GraalVM 20.2.0-dev

[meshview-log.txt](https://github.com/gluonhq/substrate/files/4706183/meshview-log.txt)

**Comment by jperedadnr** [comment]
I can reproduce the issue, just by adding an `Sphere` node.
I think the key is here:

```
[SUB] D/GraalCompiled( 6736): ERROR: 0:183: 'apply_diffuse' : no matching overloaded function found 
[SUB] D/GraalCompiled( 6736): ERROR: 0:183: '=' :  cannot convert from 'const float' to '4-component vector of float'
[SUB] D/GraalCompiled( 6736): ERROR: 2 compilation errors.  No code generated.
```

**Comment by jperedadnr** [comment]
Can you try adding this System property: `"com.sun.javafx.isEmbedded=true"` to your main and try again? It should get you further..

**Comment by mipastgt** [comment]
Yes, it works completely with that missing property set. Thanks a lot José.

**Comment by jperedadnr** [comment]
Good to know. It has been added to Substrate now, so you can just use the latest client plugin snapshot until we do a new release.
