### ISSUE TITLE
 Error LNK2001: unresolved external symbol StrictMath_xxx

### ISSUE THREAD

**Issue by phamvanthanh** [gluonhq/substrate#659]
Hi
I have tried to build with
                        <list>java.lang.StrictMath</list>
                        <list>java.lang.Math</list>
in both **jniList** and **reflectionList** but failed to link.

**Comment by jperedadnr** [comment]
Can you update your GraalVM version, from https://github.com/graalvm/graalvm-ce-dev-builds/releases, and try again? No need to add those classes to the jni/reflection lists.
