### ISSUE TITLE
PI raspios_arm64-2020-05-28 doesn't work

### ISSUE THREAD

**Issue by odbuser2** [gluonhq/substrate#676]
https://github.com/gluonhq/substrate/blob/master/README.md
refers to Raspberry PI as one of the target systems:

> GraalVM native-image tool to compile the required Java bytecode into code that can be executed on the target system (e.g. your desktop, on iOS, on a **Raspberry Pi**).

However, I don't think that the Raspberry PI is supported by the Maven plugin yet.  I haven't found an accurate description of which raspberry pi configuration is being supported (e.g. 32bit, 64bit, which distros work, etc).  It would be great if there was a compatibility and status chart that tracks all platforms.  The claims have been grand and sometimes stuff works but is often broken with an advancement of any of the pieces (substrate, gluonvm, maven plugin, openjdk release, native os changes, native os development library changes, etc.).

I've tried multiple distros but I'm now settling on Raspios_arm64:
https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2020-05-28/2020-05-27-raspios-buster-arm64.zip
but the maven plugin doesn't support it.  It would be great since the PI4 8GB uses this OS and provides a lot more potential than previous versions.

**Comment by jperedadnr** [comment]
Raspberry Pi 64 bits is supported. See documentation https://docs.gluonhq.com/#platforms_embedded and HelloPi sample https://github.com/gluonhq/gluon-samples/tree/master/HelloPi.
