### ISSUE TITLE
Static GraalVM libraries moved to a different location

### ISSUE THREAD

**Issue by tiainen** [gluonhq/substrate#679]
The static libraries provided by GraalVM have recently been moved to a different location. They used to be located in the `lib` folder, but are now moved to a platform dependent folder `lib/static/$platform-$arch`. New locations for each platform are:

- darwin: `lib/static/darwin-amd64`
- linux amd64: `lib/static/linux-amd64/glibc`
- linux aarch64: `lib/static/linux-aarch64/glibc`
- windows: `lib/static/windows-amd64`

**Comment by jperedadnr** [comment]
This is a breaking change, and while we know we are working with 20.2.0-dev, once this is merged, Substrate will stop working for those who have a GraalVM installation from a few days ago. However, Substrate doesn't work as is for new users or new GraalVM installations.

It would be great to identify the date of release of this change, and provide some logging: if the new path fails, advice to update to GraalVM newer than Jun 20 (o whatever date).

**Comment by tiainen** [comment]
That's one of the drawbacks you get when depending on a development build. Things might break and we then need to fix them. It's much easier to tell any quick adopters to download the latest GraalVM dev build and try again.

**Comment by johanvos** [comment]
can easily be fixed with 2 -L paths
