### ISSUE TITLE
generated windows image returns -1073741819 / 0xC0000005

### ISSUE THREAD

**Issue by kristofdho** [gluonhq/substrate#721]
Our application exits abruptly at an undefined time (mostly) shortly after startup with exit code -1073741819, which should correspond to 0xC0000005 `EXCEPTION_ACCESS_VIOLATION`.

If we run it in headless mode (which simply avoids calling anything javafx related) it works like a charm.

The only thing I can think of is something going wrong with JNI stuff, like storing a pointer at build-time which gets referenced at run-time, throwing this exception.

**Comment by phamvanthanh** [comment]
Similar issue. It could not work for long in windows.

**Comment by jperedadnr** [comment]
I take this issue happened with Client plugin 0.1.29? Can you try out 0.1.30?

**Comment by kristofdho** [comment]
This was still an issue on Client plugin 0.1.28, which if i'm not mistaken is the last version that's build from GraalVM 20.2-dev.

On 0.1.29 and 0.1.30 I am once again running into #597, My proposed fix from back when I logged the issue, doesn't seem to work anymore locally.

**Comment by jperedadnr** [comment]
I've noticed #597 doing `mvn client:build`, but `mvn client:compile` and then `mvn client:link` work for me. Did you try this?

**Comment by kristofdho** [comment]
I was just running `mvn package`. running `mvn client:compile client:link` does complete the build.

The issue however still persists with plugin 0.1.30 and the latest 20.3-dev build

**Comment by jperedadnr** [comment]
Ok, thanks for testing

**Comment by Plantrek** [comment]
Hi
Any solution to the problem?

**Comment by Plantrek** [comment]
[SEVERE] Process run until end failed with result: -1073741819

**Comment by DeanWookey** [comment]
We had this problem, but it seems to be working with the latest client maven plugin, 0.1.33.

**Comment by kristofdho** [comment]
substrate 0.1.33 does not fix the issue (for me), but it appears the upcomming GraalVM 20.3.0 release does fix it.

**Comment by jperedadnr** [comment]
Fixed with new GraalVM
