### ISSUE TITLE
Android didn't respond to packaging for a long time

### ISSUE THREAD

**Issue by GZYangKui** [gluonhq/substrate#724]
I cloned client demo to package an Android application. The build was successful, but the package failed and there was no error

[DEBUG INFO]
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< com.gluonhq.hello:hellogluon >--------------------
[INFO] Building hellogluon 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- client-maven-plugin:0.1.29:package (default-cli) @ hellogluon ---
[周五 7月 31 14:24:20 CST 2020][信息] ==================== PACKAGE TASK ====================
[周五 7月 31 14:24:20 CST 2020][信息] Default Android manifest generated in /home/yangkui/study/client-samples/Maven/HelloGluon/target/client/aarch64-android/gensrc/android/AndroidManifest.xml.
Consider copying it to /home/yangkui/study/client-samples/Maven/HelloGluon/src/android/AndroidManifest.xml before performing any modification
[周五 7月 31 14:24:20 CST 2020][信息] Default Android resources generated in /home/yangkui/study/client-samples/Maven/HelloGluon/target/client/aarch64-android/gensrc/android/res.
Consider copying them to /home/yangkui/study/client-samples/Maven/HelloGluon/src/android/res before performing any modification

**Comment by jperedadnr** [comment]
Can you check the logs, under `target/client/aarch64-android/gvm/log`, there should be a verbose log about the package task that explains what is was trying to do.
Also you can run with `<verbose>true</verbose>` added to the pom, to get a more verbose output.

**Comment by GZYangKui** [comment]
Thank you. The problem has been solved. It should be a network problem. Some of them have not responded for a long time
