### ISSUE TITLE
org.dom4j.DocumentException

### ISSUE THREAD

**Issue by EvokeAngle** [gluonhq/substrate#745]
a '.xml' file, absolute path d:\a.xml
run normally,
 run "mvn clean client:build client:run",
According to client-debug0.log, 
 org.dom4j.DocumentException
 	at org.dom4j.io.SAXReader.read(SAXReader.java:464)
	at org.dom4j.io.SAXReader.read(SAXReader.java:325).

**Comment by jperedadnr** [comment]
See https://docs.gluonhq.com/client/#_resourceslist
If that doesn't work, provide more details so the issue can be reproduced.
