### ISSUE TITLE
Build desktop app failed on Mac OS

### ISSUE THREAD

**Issue by MakHoCheung** [gluonhq/substrate#747]
Hello, my project uses java.net.http module and I got this when I ran nativeCompile task.
```
Fatal error:com.oracle.svm.core.util.VMError$HostedError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of javax.net.ssl.SSLContext are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked.
```
But the config "--initialize-at-build-time=javax.net.ssl.SSLContext" does not work
Can some people do me a favor?

**Comment by jperedadnr** [comment]
See https://docs.gluonhq.com/client/#_build_time_initialization, you can add a file with your build time classes (https://docs.gluonhq.com/client/#_build_time_initialization)

**Comment by MakHoCheung** [comment]
It did not work.
The `com.oracle.graal.pointsto.constraints.UnsupportedFeatureException` error is because of making the HttpClient static. 
`public static final HttpClient HTTP_CLIENT = HttpClient.newHttpClient();`

So I change the code to new HttpClient every time and my project is compiled successfully.
And thank you very much for your help
