### ISSUE TITLE
AndroidManifest in gensrc is not the final manifest

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/substrate#772]
The file under `target/client/gensrc/AndroidManifest.xml` doesn't include merged manifests for Attach and other third party jars.

The final file (after merging Attach and other third party manifests) is found at `target/client/aarch64-android/gvm/android_project/app/build/intermediates/merged_manifest/debug/out/AndroidManifest.xml`.

**Comment by mipastgt** [comment]
I have two questions concerning this issue:

1. Is the merged AndroidManifest.xml just not copied over to the advertised location or is not used at all during the build of the .apk file?
2. The documentation of the Attach PositionService states, that if you want to use this service in the background, you have to add additional information to the manifest. Why is this not also defined in the template manifest inside the service and merged into the generated manifest?  Currently it seems you are forced to manually provide a manifest just because of that (which most people will probably forget)

I try to clarify these issues because I still haven't got the PositionService working reliably again. See: https://github.com/gluonhq/attach/issues/222

**Comment by jperedadnr** [comment]
The regular scenario is:

- The user doesn't provide `src/android/AndroidManifest.xml`, then a default one ([bundled](https://github.com/gluonhq/substrate/blob/master/src/main/resources/native/android/android_project/app/src/main/AndroidManifest.xml) with Substrate) is provided. This manifest is copied as is to `target/client/gensrc/android`.

- Running the `client:package` task, the Android project updates this default manifest merging all manifests found in the libraries (typically those from [Attach](https://github.com/gluonhq/attach/blob/master/modules/position/src/main/resources/META-INF/substrate/dalvik/AndroidManifest.xml)).

- The resulting final manifest in `target/client/aarch64-android/gvm/android_project/app/build/intermediates/merged_manifest/debug/out/AndroidManifest.xml` which is used to build the apk is not copied back to `target/client/gensrc` (hence this issue). 

This works so far if the user doesn't need to modify the manifest.

A second scenario is:

- The user provides `src/android/AndroidManifest.xml`, typically after running `client:package` and copying it from `target/client/gensrc/android`. It can be modified to include whatever is needed that is not already included by third party libraries (Attach). Then the default manifest is not used anymore.

- Running the `client:package` task, the Android project updates the user manifest, merging all manifests found in the libraries. 

Therefore, this issue might not be an issue after all, since the libraries manifests are merged either way.

Regarding your question, we don't support yet an easy way to configure Attach with different settings other than what we have set as default, so in this case, modifying the manifest in the project will be the best way to do it.

**Comment by mipastgt** [comment]
Ah, I just learned something new. As far as I know it has not yet been documented anywhere (besides this place now)  that a user-provided manifest is also updated by merging in the library manifests. Up to now I thought that once you provide your own manifest you have to take care of all updates yourself. That makes it easier of course.

**Comment by AlmasB** [comment]
If I understand correctly, to close this issue, we need to move `target/client/aarch64-android/gvm/android_project/app/build/intermediates/merged_manifest/debug/out/AndroidManifest.xml` to `target/client/gensrc/AndroidManifest.xml`?

If so, please can you point me to the method where this needs to be done.

**Comment by jperedadnr** [comment]
After some more thoughts, I don't think this is an issue after all. The initial manifest added by the user is still modified when merging it with others manifest from Attach and other third party dependencies.
