### ISSUE TITLE
Jna support

### ISSUE THREAD

**Issue by alaa-abu-zidan** [gluonhq/substrate#778]
I used JNA in my application and tried generate the native image on MAC, The problem is when exporting the native libraries  I noticed that I get "lib/libjnidispatch.a" from "com.sun.jna.aix-ppc" instead of "lib/libjnidispatch.jnilib"  from  "com.sun.jna.darwin", so the linker skips it and the image wont run.
And same issue with Linux but it complains at objdump. 
https://github.com/gluonhq/substrate/blob/8789b0e935e4b13969376af1f41ce30d5855ed7a/src/main/java/com/gluonhq/substrate/target/MacOSTargetConfiguration.java#L123

**Comment by alaa-abu-zidan** [comment]
After some research it seems the problem is not only by copying the right library, there will be another issue with JNA support from Graal that will prevent the image from running, so I will close this issue.

**Comment by 18506711722** [comment]
@alaa-az  When I use oshi library, error "java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/win32-x86-64/jnidispatch.dll) not found in resource path ()",I would like to ask you how to solve the problem of JNA

**Comment by alaa-az** [comment]
@18506711722 Well actually @amahfouz1 https://github.com/amahfouz1/jna-graalvm has prepared a solution that is working just fine for Linux. Hope it will work for you, just change the resources config per platform to include the corresponding jna native library.

**Comment by amahfouz1** [comment]
@alaa-az I'm glad it worked for you if you would like to contribute your MAC or Windoes steps to the repo Readme that would be great to share with everyone. Thanks!
