### ISSUE TITLE
any way to customised Entitlements.plist?

### ISSUE THREAD

**Issue by samyc1201** [gluonhq/substrate#784]
I need to add in App Group configuration in the iOS `Entitlements.plist` file, but the doc doesn't mention how to do that. 

I found a temporary file generated after `client:link` process in the folder of `client/arm64-ios/gvm/tmp/Entitlements.plist`. But it is too late to modify this file because `client:link` process already generated the final binary.

Is this configuration features still missing at this moment?

**Comment by jperedadnr** [comment]
So far the Entitlements.plist file is autogenerated by the plugin, and it can't be changed.

Will it work if we do the same as with the Default-info.plist, placing it under `target/arm64-ios/gensrc` so it can be copied to `src/ios` for further modifications that will be taken into account if such file exist?

**Comment by samyc1201** [comment]
@jperedadnr Yes, something like `Default-info.plist` would be good. 

Currently is there any way I can enable [App Group](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_application-groups) in Gluon Substrate?

**Comment by jperedadnr** [comment]
If you want to modify Substrate and hardcode your App Group, you can do it here: https://github.com/gluonhq/substrate/blob/master/src/main/java/com/gluonhq/substrate/util/ios/CodeSigning.java#L334

Then you can build Substrate, and the Client Maven plugin to use your local build.

**Comment by samyc1201** [comment]
@jperedadnr alright thanks, I will give it a try. 

By the way, I am not very familiar with Gradle, the `readme` there doesn't mention how to build, what is the task I should run against?

**Comment by jperedadnr** [comment]
Substrate:
```
./gradlew clean build publishToMavenLocal
```
Client plugin:
```
mvn clean install
```
Then you can use `0.1.33-SNAPSHOT` in your project

**Comment by samyc1201** [comment]
ok tested by inserting the code at the suggested place, it is working, share it here just in case someone come by this as well:


```
...
dictionary.put("get-task-allow", taskAllow);
Logger.logDebug("Entitlements.plist = " + dictionary.getEntrySet());

NSArray array = new NSArray(1);
array.setValue(0, "group.xxx.yyy.zzz");
dictionary.put("com.apple.security.application-groups", array);

dictionary.saveAsXML(entitlementsPath);
return entitlementsPath;
...
```
