### ISSUE TITLE
Shouldn't Gluon Substrate abstract the Java version by default?

### ISSUE THREAD

**Issue by UltraBurstXD** [gluonhq/substrate#796]
I'm using Bellsoft 14, I was getting: `Unsupported major.minor version 58.0`. So I had to downgrade my project's Java version to 11 (by changing JDK), which is being used by graalvm. Even so, fails:` Error: Image build request failed with exit status 137`. Help, pls? The issue may be caused by graalvm, because project binaries and source were meant for Java 14. Note: I was following the samples...

**Comment by jperedadnr** [comment]
Error 137 is related to lack of memory. You might need more RAM or at least more swap memory

**Comment by UltraBurstXD** [comment]
Humm... Which RAM amount exactly?

**Comment by jperedadnr** [comment]
16 GB should work, but having 8 GB+ for swap is also convenient.
