### ISSUE TITLE
Different flow when called directly or via plugin

### ISSUE THREAD

**Issue by johanvos** [gluonhq/substrate#8]
Currently, when SubstrateDispatcher is invoked via the plugin, wrapper methods in SubstrateDispatcher are called that might do some preparation and checks before calling appropriate methods on the TargetConfiguration.
However, when calling SubstrateDispatcher via its main method, the respective methods on the TargetConfiguration are called directly.
This is error-prone, as the CI relies on the main method approach, where specific configuration might be done.
We need to minimize the code in this approach, and instead directly call the wrapper methods.

**Comment by jperedadnr** [comment]
Fixed with #9
