### ISSUE TITLE
Build nativeCompile fail with Gluon Client plugin for Gradle

### ISSUE THREAD

**Issue by SebGonzalez** [gluonhq/substrate#802]
Hi,
I tried to Gluon Client plugin for Gradle but when i launch the command "gradlew build nativeCompile" i got many errors like "Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: sun.reflect.Reflection."

I attach the log file :
[process-compile-1601620727633.log](https://github.com/gluonhq/substrate/files/5316329/process-compile-1601620727633.log)
 
I use jdk-11.0.8 and graalvm-ce-java11-20.2.0 on windows 10.

**Comment by jperedadnr** [comment]
Can you post at least your pom?

**Comment by SebGonzalez** [comment]
I don't have pom because i use gradle. I attach the build.gradle
[build.gradle.txt](https://github.com/gluonhq/substrate/files/5316946/build.gradle.txt)

**Comment by jperedadnr** [comment]
Sorry for the late reply.
The build file contains many dependencies and you have many issues. Would be good if you could isolate some of them and then reopen. 
Make sure you update to the latest Substrate and GraalVM versions.
