### ISSUE TITLE
Native-image installation errors

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/substrate#837]
Check if on Windows admin rights are required.

**Comment by abhinayagarwal** [comment]
I just ran client-gradle-plugin on Windows and it successfully downloaded native-image and created an image without admin rights.

**Comment by jperedadnr** [comment]
Yes, that's the expected behaviour, but we have some reports of people using the client plugin that didn't install `native-image` for some reason. So I'm guessing that has to do with missing admin rights (depending on the Windows machine, that is something that can be expected...)

**Comment by jperedadnr** [comment]
Not an issue
