### ISSUE TITLE
HarmonyOS

### ISSUE THREAD

**Issue by jayadevanraja** [gluonhq/substrate#847]
Please Support JavaFX In The HarmonyOS.

**Comment by johanvos** [comment]
I'd love to. But we currently lack hardware to do so. It would make very much sense to have JavaFX working on HarmonyOS though.

**Comment by rnayabed** [comment]
HarmonyOS is actually based on [Android](https://www.xda-developers.com/harmony-os-2-0-initial-version-based-on-android/), despite what Huawei claims.

Huawei being shady and outright lying clearly does not help.

**Comment by jperedadnr** [comment]
Possible an OpenJFX issue?
