### ISSUE TITLE
Documentation of Supported Platforms/Operating Systems

### ISSUE THREAD

**Issue by jayadevanraja** [gluonhq/substrate#848]
Which Operating Systems/Platforms are currently supported, and by how much (Not yet planned, Planning Stage, Alpha, Beta, Production)? Also which variants (32 bit, 64 bit).
(1) Web Platform (On browsers, in HTML, code transpiled to javascript)
(2) On top of WASM
(3) Android (With Linux kernel)
(4) GNU Operating System (With Linux kernel) - Sailfish OS, Debian/Linux, Ubuntu, etc...
(5) HarmonyOS
(6) GNU Operating System (With Hurd kernel) - Debian/Hurd etc...
(7) Macintosh OS X
(8) Windows 10
(9) iOS
(10) Chromium OS (With Linux kernel)
(11) Fuchsia OS (With Zircon kernel)
(12) dahliaOS (GNU Operating System with Linux kernel and Zircon kernel)

**Comment by abhinayagarwal** [comment]
All supported platforms are listed here: https://docs.gluonhq.com/#_platforms

**Comment by jayadevanraja** [comment]
Thanks, @abhinayagarwal .

It would be better if there is a table, with missing platforms shown as such. If, inside a table, all the above platforms are separately included with variants (32 bit ARM, 64 bit ARM, x86, amd64, SPARC, etc.) it will be more easily understood.

**Comment by abhinayagarwal** [comment]
Hi @jayadevanraja ,

Thank you for the feedback. We will try to look into this improvement.

**Comment by jperedadnr** [comment]
Table is in place: https://docs.gluonhq.com/#_platforms
