### ISSUE TITLE
"os.name" returns only "linux" on Android

### ISSUE THREAD

**Issue by rnayabed** [gluonhq/substrate#856]
`System.getProperty("os.name")` returns `linux` on android aarch64 app and on traditional linux desktop as well (Ubuntu 20.10). I am using [Gluon Client](https://github.com/gluonhq/client-maven-plugin) to compile my javafx app into a native image for Android.

It should return `android` or something which is different from `linux` as it may cause confusions when using platform specific code.

Currently, I am just specifying on runtime and have to create separate compilations specifying the Platform. 

I have also created a similar issue [here](https://github.com/oracle/graal/issues/3074).

**Comment by jperedadnr** [comment]
You can use `javafx.platform` instead. See for instance Attach's [Platform](https://github.com/gluonhq/attach/blob/master/modules/util/src/main/java/com/gluonhq/attach/util/Platform.java#L70).

**Comment by rnayabed** [comment]
> You can use `javafx.platform` instead. See for instance Attach's [Platform](https://github.com/gluonhq/attach/blob/master/modules/util/src/main/java/com/gluonhq/attach/util/Platform.java#L70).

There is a also another way. One can use `-Dgraal.targetName=android` to set their own `os.name`
