### ISSUE TITLE
Optionally allow to link with shared libc++ on Android

### ISSUE THREAD

**Issue by johanvos** [gluonhq/substrate#865]
In https://github.com/gluonhq/substrate/pull/864, we decided to link with a static libstdc++ library to fix #774 and #840

This might not be enough in case more than one library requires the symbols we link into libsubstrate.so, in which case it is more convenient to link with the shared c++ lib.

This can be a developer option, which if set, will not use the static but the shared c++ lib and also copy that in the APK.

**Comment by jperedadnr** [comment]
Fixed
