### ISSUE TITLE
-Xmx flag for android

### ISSUE THREAD

**Issue by rnayabed** [gluonhq/substrate#869]
### Expected Behavior
memory flags 

### Current Behavior
If i run the compiled app, GC doesnt work and it eats away all the memory of my phone and eventually crashes. Settings -Xmx, -Xms fixes it, but I dont see an option to do the same with the gluon client plugin (My app uses a lot of Gifs)

**Comment by jperedadnr** [comment]
The Android launcher already [sets](https://github.com/gluonhq/substrate/blob/master/src/main/resources/native/android/c/launcher.c#L69) `-Xmx4g`. Isn't it enough?

**Comment by rnayabed** [comment]
> The Android launcher already [sets](https://github.com/gluonhq/substrate/blob/master/src/main/resources/native/android/c/launcher.c#L69) `-Xmx4g`. Isn't it enough?

It is. but i want to set it very low, around ~600-700 MB. there is a [bug](https://bugs.openjdk.java.net/browse/JDK-8214838) in javafx where gif creates huge memory leaks. interestingly, when a lower heap space is set, GC keeps on clearing memory and the app itself remains stable.

Is there a way i can compile substrate with custom options, and then use it with gluon client plugin?

**Comment by jperedadnr** [comment]
If you want to give it a try you can clone Substrate. modify the `launcher.c` file as needed, and build a snapshot (`./gradlew clean publishToMavenLocal`).
Then clone the plugin, and build it locally (`mvn clean install`).
Finally, use the plugin snapshot (0.1.37-SNAPSHOT) in your project.

Alternatively, without modifying plugin/Substrate, you can hack the link goal from command line: 
- run `mvn clean -Pandroid client:build` as usual.
- see the logs under `gvm`
- modify the `launcher.c` file, compile it (with the same command line found in logs)
- and run link command line (with the same command line found in logs)
- Then run `mvn -Pandroid client:package client:install client:run`.

**Comment by rnayabed** [comment]
Thanks a lot. Closing this, as my problem has been fixed :D
