### ISSUE TITLE
Integrate graalvm native-image-agent

### ISSUE THREAD

**Issue by johanvos** [gluonhq/substrate#870]
Optionally, developers should be able to run the graalvm native-image-agent while running their application. The reflection configuration should be captured, and can later be used by Substrate.

### Expected Behavior
(Requires a new maven task, e.g. client:runagent)
When the client:runagent task is executed, the application is executed with the native-image-agent enabled. The captured configuration files are stored somewhere.
When client:compile is executed, Substrate checks if there are captured configuration files available, and merges them with the default files.

### Current Behavior
not available

### Context
This would simplify manual reflection settings for developers.

**Comment by mipastgt** [comment]
I recently tested this manually myself a couple of days ago and it worked perfectly. I just ran the application twice with the GraalVM and configured the agent to write into the META-INF/native-image folder of the main module. This resulted in 5 files (jni-, proxy-, reflect-, resource- and serialization-config.json) After clicking through all menus I was able to remove ALL my manually configured lists for the client-maven-plugin. This actually worked much better than I have expected and makes the pain of the manual configuration obsolete.

**Comment by johanvos** [comment]
Substrate currently adds a fair amount of required classes. Not everyone is able or willing to go through all the sections of an application.
Using the agent is the perfect thing to do, but it we do it from the plugin, we can make sure that the configurations are written in the correct location so that they are picked up by Substrate.
