### ISSUE TITLE
Error: Could not find option ' SerializationConfigurationFiles'

### ISSUE THREAD

**Issue by Shadow326159** [gluonhq/substrate#874]
I am trying to connect serialization-config.json but I am getting an error.

pom.xml

```
...
<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
            </plugin>

            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.5</version>
                <configuration>
                    <mainClass>${main.class}</mainClass>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.gluonhq</groupId>
                <artifactId>client-maven-plugin</artifactId>
                <version>0.1.36</version>
                <configuration>
                    <target>${client.target}</target>
                    <mainClass>${main.class}</mainClass>
                    <reflectionList>
                        <list>org.dman.Connection</list>
                        <list>org.dman.Contract</list>
                        <list>org.dman.Controller</list>
                        <list>org.dman.EncryptedConnection</list>
                        <list>org.dman.RequestThread</list>
                        <list>org.dman.TradingThread</list>
                        <list>javafx.scene.control.MenuButton</list>
                        <list>javafx.scene.control.MenuItem</list>
                        <list>javafx.scene.control.Tooltip</list>
                        <list>javafx.scene.control.Spinner</list>
                        <list>javafx.scene.control.ToggleButton</list>
                        <list>javafx.scene.control.ListView</list>
                        <list>javafx.scene.control.TextField</list>
                        <list>javafx.scene.control.PasswordField</list>
                        <list>javafx.scene.image.ImageView</list>
                    </reflectionList>
                    <nativeImageArgs>
                        <nativeImageArg>
                            -H:ReflectionConfigurationFiles = ${project.basedir}/serialization-config.json
                        </nativeImageArg>
                    </nativeImageArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>
...
```

serialization-config.json

```
[
  {
    "name":"org.dman.EncryptedConnection"
  }
]
```

I get the following:
```
[сб февр. 13 20:02:37 MSK 2021][INFO] We will now compile your code for x86_64-microsoft-windows. This may take some time.
[сб февр. 13 20:02:41 MSK 2021][INFO] [SUB] Warning: Ignoring server-mode native-image argument --no-server.
[сб февр. 13 20:02:50 MSK 2021][INFO] [SUB] Error: Could not find option ' SerializationConfigurationFiles'. Did you mean one of these: ReflectionC
onfigurationFiles SerializationConfigurationFiles SerializationConfigurationResources SerializationDenyConfigurationFiles SerializationDenyConfigur
ationResources. Use -H:PrintFlags= to list all available options.
[сб февр. 13 20:02:50 MSK 2021][INFO] [SUB] Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[сб февр. 13 20:02:51 MSK 2021][INFO] [SUB] Error: Image build request failed with exit status 1
[сб февр. 13 20:02:51 MSK 2021][INFO] Additional information: Objectfile should be called org.dman.main.obj but we didn't find that under C:\Users\
DMan\IdeaProjects\TradingRobot\target\client\x86_64-windows\gvm
[сб февр. 13 20:02:51 MSK 2021][SEVERE] Compiling failed.
```

**Comment by jperedadnr** [comment]
You can try with the native-image agent, like described here: https://stackoverflow.com/a/66019604/3956070
It will generate the config files (including serialization ones), and you don't need any extra configuration.

**Comment by Shadow326159** [comment]
> You can try with the native-image agent, like described here: https://stackoverflow.com/a/66019604/3956070
> It will generate the config files (including serialization ones), and you don't need any extra configuration.

I did it. I tried two options:
1. Leave the folder empty.
2. Leave the serialization-config.json I posted above.

In both cases, I get an error during serialization: 
`Exception in thread "JavaFX Application Thread" com.oracle.svm.core.jdk.UnsupportedFeatureError: SerializationConstructorAccessor class not found for declaringClass: java.lang.Throwable (targetConstructorClass:java.lang.Object). Usually adding java.lang.Throwable to serialization-config.json fixes the problem.`

In the gvm directory, I only see:
jniconfig-x86_64-windows.json
reflectionconfig-x86_64-windows.json
resourceconfig-x86_64-windows.json

**Comment by jperedadnr** [comment]
You need to follow these steps from the SO link:

-  Create the folder `src/main/resources/META-INF/native-image`.
- Add the agent to the javafx-maven-plugin:
```
<plugin>
        <groupId>org.openjfx</groupId>
        <artifactId>javafx-maven-plugin</artifactId>
        <version>0.0.5</version>
        <configuration>
            <mainClass>${main.class}</mainClass>
            <options>
                <option>-agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image</option>
            </options>
        </configuration>
    </plugin>
```
- Run `mvn javafx:run`, and explore all possible scenarios (so the agent can discover during runtime the classes and resources used).
- Explore the files added to `src/main/resources/META-INF/native-image`. You will find the serialization config file.

- Then run `mvn client:build`. Note that `native-image` will pick those files directly, so you won't see them under `gvm`.
- If you keep having that exception (about Throwable), add it to the config file and try again.

**Comment by Shadow326159** [comment]
> You need to follow these steps from the SO link:
> 
> * Create the folder `src/main/resources/META-INF/native-image`.
> * Add the agent to the javafx-maven-plugin:
> 
> ```
> <plugin>
>         <groupId>org.openjfx</groupId>
>         <artifactId>javafx-maven-plugin</artifactId>
>         <version>0.0.5</version>
>         <configuration>
>             <mainClass>${main.class}</mainClass>
>             <options>
>                 <option>-agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image</option>
>             </options>
>         </configuration>
>     </plugin>
> ```
> 
> * Run `mvn javafx:run`, and explore all possible scenarios (so the agent can discover during runtime the classes and resources used).
> * Explore the files added to `src/main/resources/META-INF/native-image`. You will find the serialization config file.
> * Then run `mvn client:build`. Note that `native-image` will pick those files directly, so you won't see them under `gvm`.
> * If you keep having that exception (about Throwable), add it to the config file and try again.

It's empty there.

**Comment by jperedadnr** [comment]
did you set this?
```
set JAVA_HOME=%GRAALVM_HOME%
```

**Comment by Shadow326159** [comment]
> did you set this?
> 
> ```
> set JAVA_HOME=%GRAALVM_HOME%
> ```

Yes, that's okay. The build is successful. Application work problem.

**Comment by jperedadnr** [comment]
Feel free to close this issue then.

**Comment by Shadow326159** [comment]
> Feel free to close this issue then.

I apologize.  I use a translator, so I may have expressed it incorrectly.  I wanted to say that the environment variables are set correctly.  Another project that lacks serialization builds and works fine.  And in the current project, the assembly is in progress, but when I try to serialize the object (already while the application is running), I get an exception.  The main question is why the serilization-config.json is not generated in the directory you wrote?

**Comment by jperedadnr** [comment]
When you run the native image agent, it should create the config files if they don't exist, and if you run it again, it will reuse them to merge the new content. I don't know why you get the warning in the first place:
```
native-image-agent: warning: file C:\Users\DMan\Downloads\TradingRobot\src\main\resources\META-INF\native-image\serialization-config.json for merging could not be found, skipping
```
Maybe you could try to generate an empty file in `C:\Users\DMan\Downloads\TradingRobot\src\main\resources\META-INF\native-image\serialization-config.json`:

```
[
]
```

and then run again `mvn javafx:run`? See if that works?

**Comment by Shadow326159** [comment]
> When you run the native image agent, it should create the config files if they don't exist, and if you run it again, it will reuse them to merge the new content. I don't know why you get the warning in the first place:
> 
> ```
> native-image-agent: warning: file C:\Users\DMan\Downloads\TradingRobot\src\main\resources\META-INF\native-image\serialization-config.json for merging could not be found, skipping
> ```
> 
> Maybe you could try to generate the file `C:\Users\DMan\Downloads\TradingRobot\src\main\resources\META-INF\native-image\serialization-config.json` with just this content:
> 
> ```
> [
> ]
> ```
> 
> and then run again `mvn javafx:run`? See if that works?

I tried. If you leave the folder empty, no files are generated. If you leave `serialization-config.json` there with 
```
[
]
```
, it remains unchanged.

**Comment by jperedadnr** [comment]
Make sure that when you run javafx:run you go through all the parts in your part that use serialization, so the agent can discover them.

As a test, can you try this sample? 
https://gist.githubusercontent.com/shelajev/a87adc12fcc22fee0c2195f68aeb3039/raw/d4f72e4d7606862c54f0efe1bbcb557ece369568/Main.java

When you run the agent, you should get: 

```
serialization-config.json 
[
 {   "name":"java.lang.Long"        },   
 {   "name":"java.lang.Number"      },   
 {   "name":"java.util.ArrayList"   } 
]
```
Is it the case?

**Comment by Shadow326159** [comment]
That was my fault. The application terminated abnormally and configuration files were not written. Now everything is all right.
