### ISSUE TITLE
AWT libraries are not included

### ISSUE THREAD

**Issue by alaa-az** [gluonhq/substrate#878]
GraalVM added support to AWT starting version 21, can you add awt static libs to the linking process

ON Linux I had to relink adding these -lfontmanager -ljavajpeg -llcms -lawt_headless -lawt, and remove -ljavafx_iio to make the linking process succeed.

**Comment by alaa-abu-zidan** [comment]
The GraalVM code seems to load them but not sure where the problem is.
https://github.com/oracle/graal/commit/cb492e6b8cc099ea1ed0161504d0092246fd2649

**Comment by johanvos** [comment]
We only include the libraries needed for JavaFX by default.
However, you can add any other libraries (AWT, OpenCV,...) as well. But the defaults are for generating JavaFX apps.

**Comment by alaa-abu-zidan** [comment]
My JavaFX application uses a library that uses AWT my JavaFX application is not exporting to native coz the linking is breaking due to lack of awt binaries, I am not super expert with this topic , I am not sure if the static linking of the AWT binaries should be done in graal or here.

**Comment by johanvos** [comment]
We don't include the AWT libraries by default, but at the very least we should have an option that allows to statically link in other libs (JVM or not).
@jperedadnr do we already have this option?

**Comment by alaa-abu-zidan** [comment]
Having this option would be a good solution, but also I will need an option to remove entries from dynamic libs that you add , like If I chose to statically link javajpeg, I have to remove javafx_iio from you dynamic list to avoid conflicts.

**Comment by johanvos** [comment]
Right, that is another issue, but a real important one. See https://github.com/oracle/graal/issues/3213#issuecomment-784022332 where I describe a very similar situation at the bottom.
The point is that javafx_iio should imho never contain symbols that would conflict with other libraries.

**Comment by jperedadnr** [comment]
So far, we bundle all the native libs that are discovered within the dependencies (for instance, the ones from Attach). There is a validation check (correct architecture). Other than that, we don't have an extension mechanism to modify existing linked libs in Substrate.

**Comment by kristofdho** [comment]
native awt support for windows will also be included in 21.1, which will use (shim) dlls next to the executable itself, which adds more per-build specific stuff to the linker. Can the linking command which would normally be used by native-image itself be reused/parsed/adjusted instead of completely replacing it and throwing away all auto detection of required libs graalvm already does for free?

**Comment by johanvos** [comment]
That is not that easily done, as the linking in Substrate does a number of additional processing that is specific to JavaFX. Especially on mobile and embedded, there are a bunch of specific things that need to be done.

**Comment by jperedadnr** [comment]
@alaa-az we are including `awt` and `awt_headless`. Why do you say we also need `awt_xawt`?

**Comment by alaa-az** [comment]
If you want to use any Swing classes you will need awt_xawt, awt_headless is headless, for example in the classic simple use case "if(Desktop.isDesktopSupported()) desktop = Desktop.getDesktop();" this will fail if you link headless.

**Comment by alaa-az** [comment]
And I think you may need to add <arg>-Djava.awt.headless=false</arg>  to nativeImageArgs

**Comment by jperedadnr** [comment]
@alaa-az I added to HelloFX:
```
Desktop.getDesktop();
```
and linked with `awt_xawt`, using `-Djava.awt.headless=false`.

but that failed with:
```
 /usr/bin/ld: $GRAALVM_HOME/lib/static/linux-amd64/glibc/libawt_xawt.a(XToolkit.o): undefined reference to symbol 'XFreeDeviceList'
/usr/bin/ld: /lib/x86_64-linux-gnu/libXi.so.6: error adding symbols: DSO missing from command line
```
So using `awt_xawt` will require adding to the link command other libraries.

For now we are going to include only headless support. A follow-up issue will deal with full AWT support.
