### ISSUE TITLE
Android: PasswordField shows Placeholder character instead of "●"

### ISSUE THREAD

**Issue by FlorianKirmaier** [gluonhq/substrate#885]
The Text of Passwordfields doesn't render it's "circles" correctly.
It's actually quite important because every user notices it immediately.

### Steps to Reproduce
Checkout the build here, it's your HelloWorld, 
just with an added PasswordField.
https://github.com/FlorianKirmaier/hello-gluon-ci/actions/runs/611893380

### Your Environment
Tested it on 2 phones Zenfone6 and Samsung S10e

I've also tested the following JavaFX Versions:
14-ea+7, 15.0.1 and 16-ea+7
I've also tried various fonts.

### Workarounds tried:
I've tried installing different fonts (NotoSans, Roboto Regular) but it didn't change the behavior.
A simple workaround would be great.

![WhatsApp Image 2021-03-02 at 12 26 09](https://user-images.githubusercontent.com/6547435/109648787-526c4600-7b5b-11eb-96d1-15a28cfcc0df.jpeg)

**Comment by jperedadnr** [comment]
JavaFX uses `BULLET = '\u25cf'` for the passwordField, but this symbol doesn't work with Roboto: https://www.htmlsymbols.xyz/unicode/U+25CF

Have you tried any of the other fonts that allow the symbol like Arial or Verdana?

**Comment by jperedadnr** [comment]
I've filed: https://bugs.openjdk.java.net/browse/JDK-8269026

**Comment by jperedadnr** [comment]
Bug fixed and integrated.
