### ISSUE TITLE
Graphics Device initialization failed on Linux

### ISSUE THREAD

**Issue by alaa-abu-zidan** [gluonhq/substrate#891]
Native executable is failing to start due to RuntimeException:
output with  -Dprism.verbose=true  is:

Prism pipeline init order: es2 sw
Using Double Precision Marlin Rasterizer
Using dirty region optimizations
Not using texture mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.es2.ES2Pipeline
Loading ES2 native library ... prism_es2
    succeeded.
GLFactory using com.sun.prism.es2.X11GLFactory
(X) Got class = class com.sun.prism.es2.ES2Pipeline
Failed Graphics Hardware Qualifier check.
System GPU doesn't meet the es2 pipe requirement
GraphicsPipeline.createPipeline: error initializing pipeline com.sun.prism.es2.ES2Pipeline
*** Fallback to Prism SW pipeline
Prism pipeline name = com.sun.prism.sw.SWPipeline
GraphicsPipeline.createPipeline failed for com.sun.prism.sw.SWPipeline
java.lang.ClassNotFoundException: com.sun.prism.sw.SWPipeline
    at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
    at java.lang.Class.forName(DynamicHub.java:1247)
    at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
    at java.lang.Thread.run(Thread.java:834)
    at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
    at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found

the executable runs normally when I pass -Dprism.forceGPU=true

There was an older issue with similar scenario.

Is there away to pass -Dprism.forceGPU=true when building, so I do not have to pass to the executable every time?

I tried:
`<nativeImageArgs>
          <arg>-Dprism.forceGPU=true</arg>
  </nativeImageArgs>
`
and it is not working , I still have to pass it on runtime.

Graphic card details:
65:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev ef) (prog-if 00 [VGA controller])
    Subsystem: Sapphire Technology Limited Radeon RX 570 Pulse 4GB
    Flags: bus master, fast devsel, latency 0, IRQ 67, NUMA node 0, IOMMU group 67
    Memory at 3800a0000000 (64-bit, prefetchable) [size=256M]
    Memory at 3800b0000000 (64-bit, prefetchable) [size=2M]
    I/O ports at b000 [size=256]
    Memory at d8e00000 (32-bit, non-prefetchable) [size=256K]
    Expansion ROM at 000c0000 [disabled] [size=128K]
    Capabilities: <access denied>
    Kernel driver in use: amdgpu
    Kernel modules: amdgpu

**Comment by jperedadnr** [comment]
Duplicated of #611 

If your card is not listed here, it will not enable `es2` by default. 

Then it will try `sw` pipeline (for that you need to add `<enableSWRendering>true</enableSWRendering>` to the plugin. 

Or, as you are already doing, you can still try to force `es2` using a system property. There are two ways you can do it:

- run `HelloFX -Dprism.forceGPU=true` (as runtime argument), or in your main class:

```
public static void main(String[] args) {
        System.setProperty("prism.forceGPU", "true");
        launch(args);
    }
```
