### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by Jett59** [gluonhq/substrate#946]
I was developing an app in gluon, specifically for ios. I found that, when running the app on my iphone, Voiceover could not recognise any of the controls on the screen.

### Expected Behavior

The expected behavior is that Voiceover reads the titles/accessible text of the controls when they are touched, and double tapping activates them.

### Current Behavior

At the moment Voiceover behaves as if the control was not there, not even allowing you to select it.

### Steps to Reproduce

To reproduce this issue, create a gluon app with a set of controls, like buttons, on it. Use gluon to compile and run the app. Use the platform-specific screen reader of your choice to try to read the controls.

### Your Environment

Gluon Maven client plugin 0.1.39, Graalvm ce java11 21.1.0.
Windows 10 64 bit, Macos Big Sir 11.1 amd64, iOS 14.4.2.

**Comment by jperedadnr** [comment]
This is more of an [Attach](https://github.com/gluonhq/attach) issue.

JavaFX controls are not iOS native controls, and therefore they don't have access to native accessibility features.

For those controls which under the hood implement a native control (like TextField/TextArea), it might be something that could be done in OpenJFX. For the rest, probably a native service in Attach might be the only way.

**Comment by Jett59** [comment]
Thank you @jperedadnr.
I will post an issue on attach.
