### ISSUE TITLE
Exception running JavaFX Native image using Gluon

### ISSUE THREAD

**Issue by AguwaGeorge** [gluonhq/substrate#979]
Having experienced this same issue with my own JavaFX apps, I grabbed a JavaFX web browser app code from the URL:
https://examples.javacodegeeks.com/desktop-java/javafx/javafx-webview-example/
and (without tampering with the downloaded code) I created a project in IntelliJ IDEA from the HelloFX template in gluonfx samples on Github and included all the necessary JavaFX modules in the pom.xml
Then:
mvn gluonfx:run (works perfectly, app is running smoothly), mvn gluonfx:build (successful), mvn gluonfx:nativerun (fails with error message:
**WARNING**: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @3eee3e2b'
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
Caused by: java.lang.AssertionError: java.lang.ClassNotFoundException: javafx.scene.web.WebView 
Caused by: java.lang.ClassNotFoundException: javafx.scene.web.WebView
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.122 s
[INFO] Finished at: 2021-08-09T19:31:03+01:00
[INFO] ------------------------------------------------------------------------

**Comment by jperedadnr** [comment]
Run `mvn gluonfx:runagent` before `mvn gluonfx:build`.
Note however that on Windows WebView iwith native-image s not supported yet.
